### ISSUE TITLE
tailwind plugin

### ISSUE THREAD

**Issue by electroheadfx** [muhammadsammy/tailwindcss-classnames#271] opened 2021-08-08 17:05 UTC
is tailwindcss-classnames may work with tailwind plugin, for exemple with https://daisyui.com/docs/install ?

**Comment by muhammadsammy** [comment] 2021-08-09 14:14
Duplicate of #215

You can use https://github.com/esamattis/postcss-ts-classnames project

**Closed by muhammadsammy** 2021-08-09 14:14 UTC
Labels: enhancement
